version: '3.6'
services:
  mysql:
    image: percona:latest
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: hw10
      MYSQL_USER: hw10
      MYSQL_PASSWORD: pass
    volumes:
      - ./init/percona.sql:/docker-entrypoint-initdb.d/percona.sql
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hw10
      POSTGRES_USER: hw10
      POSTGRES_PASSWORD: pass
    volumes:
      - ./init/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
